### ISSUE TITLE
quickjs-wasm-rs improvements

### ISSUE THREAD

**Issue by jianghong** [bytecodealliance/javy#295]
## Rename `Value` and `Context`
As we plan to introduce an enum that represents a `JSValue` (see below), this rename will help us disambiguate which level of representation a type is. It also helps clarify the responsibility of the type by making it more explicit that it’s simple a Wrapper/Ref.

Renames:
* `Value` -> `JSValueRef`
* `Context` -> `JSContextRef`

## Enum representation for `JSValue`
Introduce an enum that represents the underlying `quickjs::JSValue`
```rust
pub enum JSValue {
    Undefined,
    Null,
    Bool(bool),
    Int(i32),
    Float(f64),
    String(String),
    Array(Vec<JSValue>),
    Object(HashMap<String, JSValue>),
    MutArrayBuffer(*mut u8, usize), // used for readSync. need to hold a raw pointer to quickjs memory to write directly to
}

impl JSContextRef {
  ...
  pub fn deserialize(&self, val: &JSValueRef) -> Result<JSValue> { ... }
  pub fn serialize(&self, val: JSValue) -> Result<JSValueRef> { ... }
  ...
}
```
Motivations:
1) The bindings become more ergonomic, they become truly Rust based, allowing consumers to deal only with high-level and safe Rust types. 

2) The deserialization and serialization are moved to a single place, rather than having independent serialization calls at each JS <> Rust touchpoint, which becomes error prone.

## `CallbackArg` 
Introduce a `CallbackArg` struct that will be used when defining callback functions. This is an optimization so that deserialization happens lazily, only if the `CallbackArg` is needed and used. 

```rust
pub struct CallbackArg<'a> {
    inner: JSValueRef<'a>,
}

impl CallbackArg<'_> {
    pub fn value(&self) -> Result<JSValue> {
        self.value.context.deserialize(&self.inner)
    }
}


// example callback function
fn foo() -> impl FnMut(&JSContextRef, &CallbackArg, &[CallbackArg]) -> anyhow::Result<JSValue> {
    move |_: &JSContextRef, _this: &CallbackArg, args: &[CallbackArg]| {
        // deserialize args to get native Rust types
        let arg0 = args[0].value().as_i32()?;
        let arg1 = args[1].value().as_string()?;
        let arg2 = args[3].value()?.as_bool()?;
        
       // do things with args 
        ... 

        // serialize final result happens when the result gets passed back
        Ok(JSValue::String(result))
    }
}

// set function on global
global.set_property(
  "foo",
  context.wrap_callback(foo())?,
)?;
```

## Safety: Relationship between `Value` and `Context`
This change ensures that no `JSValueRef` can outlive the the `JSContextRef` that it points to and prevent any pointers to invalid memory.

```rust
// Before
pub struct Value {
    pub(super) context: *mut JSContext,
    pub(super) value: JSValue,
}

// After
pub struct JSValueRef<'a> {
    pub(super) context: &'a JSContextRef,
    pub(super) inner: JSValue,
}
```

### Tasks
- [x] Rename `Value` and `Context`
- [x] Implement `JSValue` enum and `CallbackArg` and use in callbacks
- [x] Update `Value` struct to contain reference to `Context` and add lifetimes everywhere to support this change.
- [x] Bump version and release

**Comment by jeffcharles** [comment]
This has now been completed! 🎉
