### ISSUE TITLE
New crates to support reusing API implementations

### ISSUE THREAD

**Issue by jeffcharles** [bytecodealliance/javy#310]
## Summary of changes

We'll be:
- adding a `javy` crate that exposes a `Runtime` and `Config` that wraps `JSContextRef` with the ability to access the underlying `JSContextRef` (this may be revisited in a future iteration
- adding an `apis` crate that contains reusable implementations for `console`, `TextEncoder`, `TextDecoder`, `Javy.IO.readSync`, and `Javy.IO.writeSync` that can be added to a `Runtime`

## Motivations

We want to have an easier to understand API for configuring and managing the JS environment used within Javy. We also want other developers building on top of Javy to be able to reuse our implementations of `console`, `TextEncoder`, `TextDecoder`, `Javy.IO.readSync`, and `Javy.IO.writeSync` if they want to and for it to be relatively straightforward.

## Tasks

- [x] Add `javy` crate with `Runtime` and `Config`
- [x] Add `apis` crate with all of the implementations above
- [x] Publish crates to crates.io

**Comment by jeffcharles** [comment]
This has been fully completed! 🎉
